// Post-build: writes out/sw.js, a service worker that precaches every file
// of the static export so the app (including practice mode) works offline.
// The cache name is a hash of all file contents, so each deploy gets a fresh
// cache and the old one is removed on activation.
import { createHash } from "node:crypto";
import { readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { join, relative, sep } from "node:path";
import { fileURLToPath } from "node:url";

const outDir = fileURLToPath(new URL("../out", import.meta.url));
const base = process.env.NEXT_PUBLIC_BASE_PATH ?? "";

function walk(dir) {
  return readdirSync(dir).flatMap((name) => {
    const path = join(dir, name);
    return statSync(path).isDirectory() ? walk(path) : [path];
  });
}

const hash = createHash("sha256");
const urls = [];
for (const file of walk(outDir).sort()) {
  const rel = relative(outDir, file).split(sep).join("/");
  if (rel === "sw.js" || rel.endsWith(".map")) continue;
  hash.update(rel).update(readFileSync(file));
  // Directory pages are served at their folder URL (trailingSlash: true).
  const url = rel.endsWith("index.html") ? rel.slice(0, -"index.html".length) : rel;
  urls.push(`${base}/${url}`);
}
const version = hash.digest("hex").slice(0, 12);

const sw = `// Generated by scripts/build-sw.mjs — do not edit.
const CACHE = "track-day-${version}";
const PRECACHE = ${JSON.stringify(urls)};

self.addEventListener("install", (event) => {
  event.waitUntil(caches.open(CACHE).then((cache) => cache.addAll(PRECACHE)).then(() => self.skipWaiting()));
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((k) => k.startsWith("track-day-") && k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

// Cache first. Query strings are ignored because pages are addressed as
// /tracks/view/?track=… (ADR-003) and all data lives in IndexedDB.
self.addEventListener("fetch", (event) => {
  const { request } = event;
  if (request.method !== "GET" || new URL(request.url).origin !== self.location.origin) return;
  event.respondWith(
    caches.open(CACHE).then(async (cache) => {
      const cached = await cache.match(request, { ignoreSearch: true });
      if (cached) return cached;
      try {
        return await fetch(request);
      } catch (error) {
        if (request.mode === "navigate") {
          const shell = await cache.match("${base}/", { ignoreSearch: true });
          if (shell) return shell;
        }
        throw error;
      }
    }),
  );
});
`;

writeFileSync(join(outDir, "sw.js"), sw);
console.log(`sw.js: ${urls.length} files precached (cache ${version})`);
